name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build User Service
        run: |
          echo "===== BUILDING USER SERVICE ====="
          cd user-service/user-service
          mvn clean package -DskipTests

      - name: Build Task Service
        run: |
          echo "===== BUILDING TASK SERVICE ====="
          cd task-service/task-service
          mvn clean package -DskipTests

      - name: Build User Service Docker Image
        run: |
          echo "===== BUILDING USER SERVICE DOCKER IMAGE ====="
          cd user-service/user-service
          docker build -t user-service:ci .

      - name: Build Task Service Docker Image
        run: |
          echo "===== BUILDING TASK SERVICE DOCKER IMAGE ====="
          cd task-service/task-service
          docker build -t task-service:ci .
